services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - web

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back:/back
    ports:
      - "8000:8000"
    depends_on:
      - db