
networks:
  transcendence:
    driver: bridge 

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - web
    networks:
      - transcendence

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - transcendence
  
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./back:/back
      - media_volume:/back/transcendence/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    networks:
      - transcendence

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - transcendence

volumes:
  media_volume: