POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "pascal",
    "password": "pass1234!"
}

###

POST http://localhost:8000/api/signup
Content-Type: application/json

{
    "username": "pascal", 
    "password": "pass1234!",
    "email": "pascal@gmail.com"
}

###

POST http://localhost:8000/api/logout
Content-Type: application/json
Authorization: Token 89f0bb3b077b3e9885ad288909ed44baac0fbfb4

{}

###

GET http://localhost:8000/api/test_token/
Content-Type: application/json
Authorization: Token 89f0bb3b077b3e9885ad288909ed44baac0fbfb4

{}

###