POST https://localhost/api/login
Content-Type: application/json

{
    "username": "pascal",
    "password": "Pascal1234!"
}

###

POST https://localhost/api/signup
Content-Type: application/json

{
    "username": "pascal", 
    "password": "Pascal1234!",
    "email": "pascal@gmail.com"
}

###

POST https://localhost/api/logout
Content-Type: application/json
Cookie: jwt=553cface1f9311a16878b1c9c4cfdf7ffc9a88cf

{}

###

GET https://localhost/api/profile
Content-Type: application/json
Cookie: jwt=a1d155741ccdac75ec1fd8f3f303ae67c80c9189

###

PUT https://localhost/api/update_user
Content-Type: application/json
Cookie: jwt=21cb4ac75ce59478cb675b1c27dd68738dac1ed5

{
    "password": "Pascal333@@@!",
    "username": "big noob",
    "email": "pascalobispo@gmail.com"
}

###

POST https://localhost/api/add_friend
Content-Type: application/json
Cookie: jwt=2cdceb32f3adc8aeaa3dd29ce5e2ce77738d4bc6

{
    "username": "pascal34"
}

###

POST https://localhost/api/remove_friend
Content-Type: application/json
Cookie: jwt=2cdceb32f3adc8aeaa3dd29ce5e2ce77738d4bc6

{
    "username": "pascal2"
}

###

GET https://localhost/api/friends_list
Content-Type: application/json
Cookie: jwt=a1d155741ccdac75ec1fd8f3f303ae67c80c9189

###

GET https://localhost/api/users_list/
Content-Type: application/json
Cookie: jwt=e39b493e181c827d20faa60bb1322ab180b2f5cb

###