POST https://localhost/api/login
Content-Type: application/json

{
    "username": "pascal",
    "password": "Pascal1234!"
}

###

POST https://localhost/api/signup
Content-Type: application/json

{
    "username": "pascal2", 
    "password": "Pascal1234!",
    "email": "pascal2@gmail.com"
}

###

POST https://localhost/api/logout
Content-Type: application/json
Cookie: jwt=2122e1cf9af50899c5e0240c180cc1440c28e111

{}

###

GET https://localhost/api/profile
Content-Type: application/json
Cookie: jwt=3464dab5b29ea5576b277276ca583b37c586de61

###

PUT https://localhost/api/update_user
Content-Type: application/json
Cookie: jwt=21cb4ac75ce59478cb675b1c27dd68738dac1ed5

{
    "password": "Pascal333@@@!",
    "username": "big noob",
    "email": "pascalobispo@gmail.com"
}

###

POST https://localhost/api/add_friend
Content-Type: application/json
Cookie: jwt=81df7ab78c409d78b2610e77c517551c572c7f4d

{
    "username": "pascal3"
}

###

POST https://localhost/api/remove_friend
Content-Type: application/json
Cookie: jwt=2cdceb32f3adc8aeaa3dd29ce5e2ce77738d4bc6

{
    "username": "pascal2"
}

###

GET https://localhost/api/friends_list
Content-Type: application/json
Cookie: jwt=81df7ab78c409d78b2610e77c517551c572c7f4d

###

GET https://localhost/api/users_list/
Content-Type: application/json
Cookie: jwt=e39b493e181c827d20faa60bb1322ab180b2f5cb

###

POST https://localhost/api/record_pacman_match/
Content-Type: application/json
Cookie: jwt=3464dab5b29ea5576b277276ca583b37c586de61

{
    "pacman_player": 1,
    "ghost_player": 2,
    "map_name": "map3",
    "match_duration": 11,
    "winner": 2,
    "pacman_score": 50
}

###

GET https://localhost/api/pacman_matches_history/
Content-Type: application/json
Cookie: jwt=3464dab5b29ea5576b277276ca583b37c586de61

###

GET https://localhost/api/pacman_stats/
Content-Type: application/json
Cookie: jwt=3464dab5b29ea5576b277276ca583b37c586de61

###

PUT https://localhost/api/pacman_endless_update
Content-Type: application/json
Cookie: jwt=3464dab5b29ea5576b277276ca583b37c586de61

{
    "max_endless_score": 10000
}