# Generated by Django 5.1 on 2024-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'e-mail-empty-error', 'unique': 'email-exists-error'}, max_length=254, unique=True),
        ),
    ]
