# Generated by Django 5.1 on 2024-08-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
