# Generated by Django 5.1 on 2024-08-30 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_customuser_online_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacmanMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=255)),
                ('pacman_score_goal', models.IntegerField()),
                ('match_duration', models.DurationField()),
                ('pacman_score', models.IntegerField()),
                ('ghost_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacman_matches_as_ghost', to=settings.AUTH_USER_MODEL)),
                ('pacman_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacman_matches_as_pacman', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacman_matches_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
