# Generated by Django 5.1.1 on 2024-09-09 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_customuser_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_endless_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pacman_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pacman_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_ai_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_pvp_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_tournament_played',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AIPongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=255)),
                ('ai_level', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('match_score', models.CharField(max_length=255)),
                ('match_duration', models.DurationField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PacmanMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacman_player', models.CharField(max_length=255)),
                ('pacman_character', models.CharField(max_length=255)),
                ('ghost_player', models.CharField(max_length=255)),
                ('ghost_character', models.CharField(max_length=255)),
                ('map_name', models.CharField(max_length=255)),
                ('match_duration', models.DurationField()),
                ('winner', models.CharField(max_length=255)),
                ('pacman_score', models.IntegerField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PvPongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=255)),
                ('player_two', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('match_score', models.CharField(max_length=255)),
                ('match_duration', models.DurationField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranking', models.TextField()),
                ('duration', models.DurationField()),
                ('matches', models.ManyToManyField(to='user_management.pvpongmatch')),
            ],
        ),
    ]
