# Generated by Django 5.1 on 2024-08-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_pacmanmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacmanmatch',
            name='pacman_score_goal',
        ),
    ]
