# Generated by Django 5.1 on 2024-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_remove_pacmanmatch_pacman_score_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_endless_score',
            field=models.IntegerField(default=0),
        ),
    ]
