# Generated by Django 5.1.1 on 2024-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_customuser_max_endless_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('match_score', models.CharField(max_length=255)),
                ('match_duration', models.DurationField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PvPongMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(max_length=255)),
                ('player_two', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('match_score', models.CharField(max_length=255)),
                ('match_duration', models.DurationField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_ai_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_ai_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_pvp_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_pvp_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_pong_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_tournament_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_tournament_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranking', models.TextField()),
                ('matches', models.ManyToManyField(to='user_management.pvpongmatch')),
            ],
        ),
    ]
