version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  
  web:
    build: .
    restart: always
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    depends_on:
      - db